# Generated by Django 3.0.5 on 2020-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_about', models.TextField()),
                ('first_about', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('website', models.TextField(max_length=100)),
                ('city', models.TextField()),
                ('freelancer', models.BooleanField(default=True)),
                ('profile_image', models.ImageField(upload_to='profile_image')),
            ],
        ),
    ]
