# Generated by Django 3.0.5 on 2020-04-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='degree',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
