# Generated by Django 3.0.5 on 2020-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200406_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='last_about',
            field=models.TextField(default=0),
        ),
    ]
