# Generated by Django 3.0.5 on 2020-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_last_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
