# Generated by Django 3.0.5 on 2020-04-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200406_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_facts', models.TextField(max_length=100)),
                ('facts_numbers1', models.IntegerField()),
                ('facts_numbers2', models.IntegerField()),
                ('facts_numbers3', models.IntegerField()),
                ('facts_numbers4', models.IntegerField()),
                ('facts_text_strong_numbers1', models.TextField(max_length=100)),
                ('facts_text_strong_numbers2', models.TextField(max_length=100)),
                ('facts_text_strong_numbers3', models.TextField(max_length=100)),
                ('facts_text_strong_numbers4', models.TextField(max_length=100)),
                ('facts_text_phara_numbers1', models.TextField(max_length=100)),
                ('facts_text_phara_numbers2', models.TextField(max_length=100)),
                ('facts_text_phara_numbers3', models.TextField(max_length=100)),
                ('facts_text_phara_numbers4', models.TextField(max_length=100)),
            ],
        ),
    ]
