# Generated by Django 3.0.5 on 2020-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200406_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_main', models.TextField()),
                ('facts_main', models.TextField()),
                ('skill_main', models.TextField()),
                ('resume_main', models.TextField()),
                ('project_main', models.TextField()),
                ('service_main', models.TextField()),
                ('testimonials_main', models.TextField()),
                ('contact_main', models.TextField()),
            ],
        ),
    ]
