# Generated by Django 3.0.5 on 2020-04-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_main_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill_percentage_number1',
            new_name='skill_percentage',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='main_skills',
            new_name='skillset',
        ),
        migrations.RemoveField(
            model_name='about',
            name='main_about',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='main_facts',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='skill_number1',
        ),
    ]
