# Generated by Django 3.0.5 on 2020-04-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200406_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facts',
            old_name='facts_numbers1',
            new_name='facts_numbers',
        ),
        migrations.RenameField(
            model_name='facts',
            old_name='facts_text_phara_numbers1',
            new_name='facts_text_phara',
        ),
        migrations.RenameField(
            model_name='facts',
            old_name='facts_text_phara_numbers2',
            new_name='facts_text_strong',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_numbers2',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_numbers3',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_numbers4',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_text_phara_numbers3',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_text_phara_numbers4',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_text_strong_numbers1',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_text_strong_numbers2',
        ),
        migrations.RemoveField(
            model_name='facts',
            name='facts_text_strong_numbers3',
        ),
    ]
