# Generated by Django 3.0.5 on 2020-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200406_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='facts',
            name='facts_emog_icon',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
