# Generated by Django 3.0.5 on 2020-04-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_facts_facts_emog_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillset', models.TextField()),
                ('skill_percentage', models.IntegerField()),
            ],
        ),
    ]
