# Generated by Django 3.0.5 on 2020-04-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_skills1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills1',
            old_name='skill_percentage',
            new_name='skill_percentage1',
        ),
        migrations.RenameField(
            model_name='skills1',
            old_name='skillset',
            new_name='skillset1',
        ),
    ]
