# Generated by Django 3.0.5 on 2020-04-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200406_1615'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills1',
            new_name='Skills_left',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skills_right',
        ),
        migrations.RenameField(
            model_name='skills_left',
            old_name='skill_percentage1',
            new_name='skill_percentage_left',
        ),
        migrations.RenameField(
            model_name='skills_left',
            old_name='skillset1',
            new_name='skillset_left',
        ),
        migrations.RenameField(
            model_name='skills_right',
            old_name='skill_percentage',
            new_name='skill_percentage_right',
        ),
        migrations.RenameField(
            model_name='skills_right',
            old_name='skillset',
            new_name='skillset_right',
        ),
    ]
