# Generated by Django 3.0.5 on 2020-04-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200406_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_emog_icon', models.TextField()),
                ('services_heading', models.TextField(max_length=200)),
                ('services_text_phara', models.TextField(max_length=300)),
            ],
        ),
    ]
