# Generated by Django 3.0.5 on 2020-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonials_quote', models.TextField()),
                ('testimonials_name', models.TextField(max_length=100)),
                ('testimonials_image', models.ImageField(upload_to='', verbose_name='testimonials_image')),
                ('testimonials_desigination', models.TextField(max_length=100)),
            ],
        ),
    ]
