# Generated by Django 3.0.5 on 2020-04-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_call', models.TextField()),
            ],
        ),
    ]
