# Generated by Django 3.0.5 on 2020-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resuma_bullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuma_bullet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resuma_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuma_heading', models.TextField()),
                ('resuma_date_till', models.TextField(blank=True)),
                ('resuma_discription', models.TextField(blank=True)),
            ],
        ),
    ]
