# Generated by Django 3.0.5 on 2020-04-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_resuma_bullet_resuma_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resuma_bullet_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuma_bullet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resuma_main_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuma_heading_pro', models.TextField()),
                ('resuma_date_till_pro', models.TextField(blank=True)),
                ('resuma_discription_pro', models.TextField(blank=True)),
            ],
        ),
    ]
