# Generated by Django 3.0.5 on 2020-04-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_resuma_bullet_pro_resuma_main_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resuma_bullet_pro',
            old_name='resuma_bullet',
            new_name='resuma_bullet_pro',
        ),
    ]
