# Generated by Django 3.0.5 on 2020-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200407_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resuma_education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuma_education_heading', models.TextField()),
                ('resuma_education_date_till', models.TextField(blank=True)),
                ('resuma_education_location', models.TextField(blank=True)),
                ('resuma_education_paragraph', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resuma_professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuma_Professional_heading', models.TextField()),
                ('resuma_Professional_date_till', models.TextField(blank=True)),
                ('resuma_Professional_discription', models.TextField(blank=True)),
                ('resuma_professional_bullet', models.TextField(blank=True)),
                ('resuma_professional_bullet1', models.TextField(blank=True)),
                ('resuma_professional_bullet2', models.TextField(blank=True)),
                ('resuma_professional_bullet3', models.TextField(blank=True)),
                ('resuma_professional_bullet4', models.TextField(blank=True)),
                ('resuma_professional_bullet5', models.TextField(blank=True)),
                ('resuma_professional_bullet6', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resuma_bullet',
        ),
        migrations.DeleteModel(
            name='Resuma_bullet_pro',
        ),
        migrations.DeleteModel(
            name='Resuma_main',
        ),
        migrations.DeleteModel(
            name='Resuma_main_pro',
        ),
    ]
