# Generated by Django 3.0.5 on 2020-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200408_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resuma_professional',
            name='resuma_professional_bullet6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
