# Generated by Django 3.0.5 on 2020-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_resuma_summery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_name', models.CharField(max_length=100)),
                ('contact_form_email', models.EmailField(max_length=200)),
                ('contact_form_subject', models.TextField(max_length=100)),
                ('contact_form_message', models.TextField()),
            ],
        ),
    ]
