# Generated by Django 3.0.5 on 2020-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_Symbole', models.TextField()),
                ('table_Price', models.IntegerField()),
                ('table_Yesterday_close', models.IntegerField()),
                ('table_Yesterday_ralley_percentage', models.IntegerField()),
                ('table_today_open', models.IntegerField()),
                ('table_extra', models.TextField()),
            ],
        ),
    ]
