# Generated by Django 3.0.5 on 2020-04-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200410_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_content',
            name='table_Price',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_Yesterday_close',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_Yesterday_ralley_percentage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_today_open',
            field=models.TextField(blank=True),
        ),
    ]
