# Generated by Django 3.0.5 on 2020-04-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200410_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_content',
            name='table_Price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_Yesterday_close',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_Yesterday_ralley_percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_extra',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='table_content',
            name='table_today_open',
            field=models.FloatField(blank=True),
        ),
    ]
