# Generated by Django 3.0.5 on 2020-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200412_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_content',
            name='table_extra',
            field=models.TextField(blank=True),
        ),
    ]
