# Generated by Django 3.0.5 on 2020-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_table_content_table_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_pattern_trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_pattern_trading_img', models.ImageField(upload_to='project/pattern_trading')),
                ('project_pattern_trading_redirect', models.TextField()),
            ],
        ),
    ]
