# Generated by Django 3.0.5 on 2020-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
