# Generated by Django 3.0.5 on 2020-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gap_down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_down_current_price', models.IntegerField()),
                ('gap_down_open', models.IntegerField(default=0)),
                ('gap_down_percentage', models.IntegerField()),
                ('gap_down_yesterday_low', models.IntegerField()),
                ('gap_down_yesterday_symbol', models.TextField()),
                ('gap_down_today_symbol', models.TextField()),
                ('gap_down_chat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gap_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_up_current_price', models.IntegerField()),
                ('gap_up_open', models.IntegerField(default=0)),
                ('gap_up_percentage', models.IntegerField()),
                ('gap_up_yesterday_high', models.IntegerField()),
                ('gap_up_yesterday_symbol', models.TextField()),
                ('gap_up_today_symbol', models.TextField()),
                ('gap_up_chat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Red_green_red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_green_red_current_price', models.IntegerField()),
                ('red_green_red_open', models.IntegerField(default=0)),
                ('red_green_red_percentage_change', models.IntegerField()),
                ('red_green_red_difference', models.IntegerField()),
                ('red_green_red_yesterday_high', models.IntegerField()),
                ('red_green_red_yesterday_symbol', models.TextField()),
                ('red_green_red_chat', models.TextField()),
            ],
        ),
    ]
