# Generated by Django 3.0.5 on 2020-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20200412_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='red_green_red',
            name='red_green_red_today_symbol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
