# Generated by Django 3.0.5 on 2020-04-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_red_green_red_red_green_red_today_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='trading_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_base_image', models.ImageField(upload_to='trading_base')),
                ('trading_base_caption', models.TextField()),
                ('trading_base_sub_cap', models.TextField(blank=True)),
                ('trading_base_discription', models.TextField()),
                ('trading_base_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
