# Generated by Django 3.0.5 on 2020-04-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trading_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading_base_imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_trading_base', models.ImageField(upload_to='trading_base/trading_base_imgs')),
            ],
        ),
        migrations.RenameModel(
            old_name='trading_base',
            new_name='Portfolio',
        ),
    ]
