# Generated by Django 3.0.5 on 2020-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20200414_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading_base_imgs',
            name='strstigy_name',
            field=models.TextField(default=0),
        ),
    ]
