# Generated by Django 3.0.5 on 2020-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trading_base_imgs_strstigy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_data_open', models.IntegerField(blank=True, default=0, null=True)),
                ('live_data_percentage_change', models.IntegerField(blank=True, default=0, null=True)),
                ('live_data_high', models.IntegerField(blank=True, default=0, null=True)),
                ('live_data_low', models.IntegerField(blank=True, default=0, null=True)),
                ('live_data_volume', models.IntegerField(blank=True, default=0, null=True)),
                ('live_data_symbole', models.TextField(blank=True, null=True)),
                ('live_data_ltp', models.IntegerField(blank=True, default=0, null=True)),
                ('live_data_chat', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
