# Generated by Django 3.0.5 on 2020-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_live_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_data',
            name='live_data_percentage_change',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
