# Generated by Django 3.0.5 on 2020-04-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20200415_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_trading_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_trading_base_main_heading', models.TextField()),
                ('main_trading_base_trading1', models.TextField()),
                ('main_trading_base_trading2', models.TextField()),
                ('main_trading_base_scanner', models.TextField()),
            ],
        ),
    ]
