# Generated by Django 3.0.5 on 2020-04-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_main_trading_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trading_base_imgs',
        ),
        migrations.RemoveField(
            model_name='main_trading_base',
            name='main_trading_base_scanner',
        ),
        migrations.RemoveField(
            model_name='main_trading_base',
            name='main_trading_base_trading1',
        ),
        migrations.RemoveField(
            model_name='main_trading_base',
            name='main_trading_base_trading2',
        ),
    ]
