# Generated by Django 3.0.5 on 2020-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_auto_20200416_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gap_down',
            old_name='gap_down_chat',
            new_name='gap_down_chat1_zerodha',
        ),
        migrations.RenameField(
            model_name='gap_up',
            old_name='gap_up_chat',
            new_name='gap_up_chat_economictimes',
        ),
        migrations.RenameField(
            model_name='live_data',
            old_name='live_data_chat',
            new_name='live_data_chat_economictimes',
        ),
        migrations.RenameField(
            model_name='red_green_red',
            old_name='red_green_red_chat',
            new_name='red_green_red_chat_economictimes',
        ),
        migrations.AddField(
            model_name='gap_down',
            name='gap_down_chat_economictimes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gap_down',
            name='gap_down_chat_maeketmojo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gap_up',
            name='gap_up_chat_maeketmojo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gap_up',
            name='gap_up_chat_zerodha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live_data',
            name='live_data_chat_maeketmojo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='live_data',
            name='live_data_chat_zerodha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='red_green_red',
            name='red_green_red_chat_maeketmojo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='red_green_red',
            name='red_green_red_chat_zerodha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
