# Generated by Django 3.0.5 on 2020-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20200425_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
