# Generated by Django 3.0.5 on 2020-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_blog_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post_steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='step',
            field=models.ManyToManyField(to='trading.Blog_Post_steps'),
        ),
    ]
