# Generated by Django 3.0.5 on 2020-05-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_auto_20200505_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='step',
        ),
        migrations.DeleteModel(
            name='Blog_Post_steps',
        ),
    ]
