# Generated by Django 3.0.5 on 2020-05-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20200505_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Historic_data_open', models.IntegerField(blank=True, default=0, null=True)),
                ('Historic_data_percentage_change', models.TextField(blank=True, default=0, null=True)),
                ('Historic_data_high', models.IntegerField(blank=True, default=0, null=True)),
                ('Historic_data_low', models.IntegerField(blank=True, default=0, null=True)),
                ('Historic_data_volume', models.IntegerField(blank=True, default=0, null=True)),
                ('Historic_data_symbole', models.TextField(blank=True, null=True)),
                ('Historic_data_ltp', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
