# Generated by Django 3.0.5 on 2020-05-24 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_historic_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Post_catogory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='catogory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Blog_Post_catogory'),
        ),
    ]
