# Generated by Django 3.0.5 on 2020-05-24 14:12

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_auto_20200524_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post_steps',
            name='steps',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
