# Generated by Django 3.0.5 on 2020-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_blog_post_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='trading_base_image',
            field=models.ImageField(upload_to='trading/trading_base'),
        ),
    ]
