# Generated by Django 3.0.8 on 2020-07-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apikeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=1000, null=True)),
                ('api_secret', models.CharField(max_length=1000, null=True)),
                ('access_token', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
