# Generated by Django 3.0.8 on 2020-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0002_apikeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='access_token',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='api_secret',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
