# Generated by Django 3.0.8 on 2020-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0003_auto_20200721_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='api_secret',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
