# Generated by Django 3.0.8 on 2020-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0004_auto_20200721_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='api_key',
            field=models.TextField(blank=True, default='hdtlbz2j74tym170', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='api_secret',
            field=models.TextField(blank=True, default='cdh6zl7tjiokssi1acwt46nft3z6nxx1', max_length=1000, null=True),
        ),
    ]
