# Generated by Django 3.0.8 on 2020-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0006_user_stock_keys_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='a_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
